<?php

namespace AppBundle\Repository;

/**
 * TicketAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketAmountRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneByAge(\DateTime $birthday)
	{
		$today = new \DateTime();
		$interval = $today->diff($birthday);

		$age = $interval->format('%y');

		return $this->createQueryBuilder('a')
			->where("a.ageConditionStart <= :start")->setParameter('start', $age)
			->andWhere("a.ageConditionEnd > :end")->setParameter('end', $age)
			->getQuery()->getSingleResult()
			;
	}
}
