<?php

namespace AppBundle\Repository;
use AppBundle\Entity\BookingEntityInterface;

/**
 * TicketAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
}
