<?php

namespace AppBundle\Repository;

/**
 * TicketAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param integer $hour limit between 0 and 24
     */
    public function findTicketTypeAvailableFor($hour)
    {
        return $this->createQueryBuilder("t")
            ->where("t.limitHour > :hour")->setParameter('hour', $hour)
            ->getQuery()->getResult();
    }
}
