<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * TicketAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketAmountRepository extends EntityRepository
{
	public function findOneByAge(\DateTime $birthday, $specialAmount = false)
	{
		$today = new \DateTime();
		$interval = $today->diff($birthday);

		$age = $interval->format('%y');

		return $this->createQueryBuilder('t')
			->where("t.ageConditionStart <= :start")->setParameter('start', $age)
			->andWhere("t.ageConditionEnd > :end")->setParameter('end', $age)
			->andWhere("t.specialAmount = :specialAmount")->setParameter('specialAmount', $specialAmount)
			->getQuery()->getOneOrNullResult()
			;
	}

	public function countAllTicket()
    {
        return $this->createQueryBuilder("t")->select("count(t.id)")->getQuery()->getSingleScalarResult();
    }
}
