services:
    app.entity.booking:
        class: AppBundle\Entity\Booking
    app.form.type.booking:
        class: AppBundle\Form\Type\BookingType
    app.manager.booking:
        class: AppBundle\Manager\BookingManager
        arguments: ["@doctrine.orm.entity_manager", "@app.form.type.booking" ,"@app.entity.booking"]
    app.form.handler.booking:
        class: AppBundle\Form\Handler\BookingFormHandler
        arguments: ["@app.manager.booking", "@form.factory", "@request_stack"]

